# This file is a template that explains the available client settings and their options. All options selected in this
# file are the defaults. To have the client actually use your settings, rename this file to "settings.toml". Every
# release will contain "settings.tmpl.toml" so you can reference it to see if there is anything new.

[settings]

# "item_display" configures how items are displayed in your game.
#
# "full": Pseudoregalia items look vanilla, items from other games look different based on their classification.
# "generic_non_pseudo": Pseudoregalia items look vanilla, items from other games all look the same.
# "generic_all": All items look the same.
item_display = "full"

# "death_link" configures whether to opt in to the death link system.
#
# true: When you die, everyone dies. Of course the reverse is true too.
# false: Your deaths are yours alone. There is no one else to blame.
death_link = false
